package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.ItemStockDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemStockDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int insert(ItemStockDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int insertSelective(ItemStockDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    ItemStockDTO selectByPrimaryKey(Integer id);

    ItemStockDTO selectByItemId(Integer itemId);

    List<ItemStockDTO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int updateByPrimaryKeySelective(ItemStockDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int updateByPrimaryKey(ItemStockDTO record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}