package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.ItemStockDTO;
import java.util.List;

public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Wed Feb 26 21:42:09 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Wed Feb 26 21:42:09 CST 2020
     */
    int insert(ItemStockDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Wed Feb 26 21:42:09 CST 2020
     */
    ItemStockDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Wed Feb 26 21:42:09 CST 2020
     */
    List<ItemStockDTO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Wed Feb 26 21:42:09 CST 2020
     */
    int updateByPrimaryKey(ItemStockDTO record);
}