package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.ItemDTO;

import java.util.List;

public interface ItemDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int insert(ItemDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int insertSelective(ItemDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    ItemDTO selectByPrimaryKey(Integer id);

    ItemDTO selectByTitle(String titile);

    List<ItemDTO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int updateByPrimaryKeySelective(ItemDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Fri Feb 28 16:58:42 CST 2020
     */
    int updateByPrimaryKey(ItemDTO record);

    boolean increaseSales(Integer itemId, Integer amount);
}