package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.OrderInfoDTO;

import java.util.List;

public interface OrderInfoDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Feb 28 21:31:31 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Feb 28 21:31:31 CST 2020
     */
    int insert(OrderInfoDTO record);

    Long getLen();

    List<OrderInfoDTO> getList(Integer index, Integer pageSize);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Feb 28 21:31:31 CST 2020
     */
    int insertSelective(OrderInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Feb 28 21:31:31 CST 2020
     */
    OrderInfoDTO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Feb 28 21:31:31 CST 2020
     */
    int updateByPrimaryKeySelective(OrderInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Feb 28 21:31:31 CST 2020
     */
    int updateByPrimaryKey(OrderInfoDTO record);
}