package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.PromoDTO;

public interface PromoDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Wed Mar 11 15:36:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Wed Mar 11 15:36:59 CST 2020
     */
    int insert(PromoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Wed Mar 11 15:36:59 CST 2020
     */
    int insertSelective(PromoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Wed Mar 11 15:36:59 CST 2020
     */
    PromoDTO selectByPrimaryKey(Integer id);

    PromoDTO selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Wed Mar 11 15:36:59 CST 2020
     */
    int updateByPrimaryKeySelective(PromoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Wed Mar 11 15:36:59 CST 2020
     */
    int updateByPrimaryKey(PromoDTO record);
}