package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.SequenceInfoDTO;

public interface SequenceInfoDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Mon Mar 02 17:51:55 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Mon Mar 02 17:51:55 CST 2020
     */
    int insert(SequenceInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Mon Mar 02 17:51:55 CST 2020
     */
    int insertSelective(SequenceInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Mon Mar 02 17:51:55 CST 2020
     */
    SequenceInfoDTO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Mon Mar 02 17:51:55 CST 2020
     */
    int updateByPrimaryKeySelective(SequenceInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Mon Mar 02 17:51:55 CST 2020
     */
    int updateByPrimaryKey(SequenceInfoDTO record);

    SequenceInfoDTO getSequenceByName(String name);
}