package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.StockLogDTO;

public interface StockLogDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Fri Mar 20 23:23:40 CST 2020
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Fri Mar 20 23:23:40 CST 2020
     */
    int insert(StockLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Fri Mar 20 23:23:40 CST 2020
     */
    int insertSelective(StockLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Fri Mar 20 23:23:40 CST 2020
     */
    StockLogDTO selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Fri Mar 20 23:23:40 CST 2020
     */
    int updateByPrimaryKeySelective(StockLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Fri Mar 20 23:23:40 CST 2020
     */
    int updateByPrimaryKey(StockLogDTO record);
}