package com.hackhu.seckill.dao;

import com.hackhu.seckill.dto.UserPasswordDTO;
import java.util.List;

public interface UserPasswordDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Feb 24 16:12:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Feb 24 16:12:50 CST 2020
     */
    int insert(UserPasswordDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Feb 24 16:12:50 CST 2020
     */
    UserPasswordDTO selectByPrimaryKey(Integer id);
    UserPasswordDTO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Feb 24 16:12:50 CST 2020
     */
    List<UserPasswordDTO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Feb 24 16:12:50 CST 2020
     */
    int updateByPrimaryKey(UserPasswordDTO record);
}